# GoReleaser configuration
# https://goreleaser.com

version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: amazon-cli
    main: .
    binary: amazon-cli
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: amazon-cli
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"

release:
  github:
    owner: zkwentz
    name: amazon-cli
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"

brews:
  - name: amazon-cli
    repository:
      owner: zkwentz
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/zkwentz/amazon-cli"
    description: "CLI for Amazon shopping - orders, returns, purchases, subscriptions"
    license: "MIT"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    test: |
      system "#{bin}/amazon-cli", "--version"
    install: |
      bin.install "amazon-cli"
